James/b/1657
shesha-io/shesha-framework pull request #1691
Opened 2024-06-13 06:55 UTC by James-Baloyi

#1657

2024-06-13 09:14 UTC, IvanIlyichev requested changes
Hi @James-Baloyi. The code is not compilable. Please create pull requests only after successful local build and testing

2024-06-13 09:29 UTC, James-Baloyi commented
Hi @IvanIlyichev, sorry it was a small oversight. I've fixed the unused imports

2024-06-19 12:13 UTC, IvanIlyichev requested changes
Hi @James-Baloyi. Check inline comments and make changes

2024-06-19 12:13 UTC, IvanIlyichev commented on shesha-reactjs/src/designer-components/iconPicker/iconPickerWrapper.tsx
> +        return color;
Hi @James-Baloyi if this change is not a mistake - remove unneeded useMemo and use value directly

2024-06-19 12:13 UTC, IvanIlyichev commented on shesha-reactjs/src/designer-components/iconPicker/iconPickerWrapper.tsx
> +        return borderColor;
Hi @James-Baloyi if this change is not a mistake - remove unneeded useMemo and use value directly

2024-06-19 12:13 UTC, IvanIlyichev commented on shesha-reactjs/src/designer-components/iconPicker/iconPickerWrapper.tsx
> +        return defaultValue;
Hi @James-Baloyi if this change is not a mistake - remove unneeded useMemo and use value directly

2024-06-19 13:54 UTC, James-Baloyi commented
@IvanIlyichev  the changes have been implemented

2024-06-20 08:05 UTC, IvanIlyichev approved these changes

2024-06-20 08:05 UTC, merged