Allow User Registration and Authentication behavior configurable
shesha-io/shesha-framework pull request #2110
Opened 2024-09-03 13:28 UTC by OmolemoBlessingLethuloe

2024-09-03 13:38 UTC, OmolemoBlessingLethuloe commented
Related Issue: https://github.com/shesha-io/shesha-framework/issues/2073

2024-09-04 06:21 UTC, IvanIlyichev requested changes
Hi @OmolemoBlessingLethuloe. Back-end build fails and I can't finish review in details, but I added some inline comments. Please fix build and review them. Additional notes:
1. Replace usage of `window.location.search` with `query`
2. Replace usage of `globalState` with application context or page context, contact Alex for details
3. Avoid usage of field names when access setting fields, use dot notation instead. Even if we have no intellisense support there currently we'll improve it in future
4. Remove all console.log from built in forms included into your package

2024-09-04 06:21 UTC, IvanIlyichev commented on shesha-reactjs/src/providers/auth/index.tsx
> +          .then((response) => checkRegistrationCompletion(response))
Hi @OmolemoBlessingLethuloe. This chain of calls may be broken by the redirect. Please review the code and test it  thoroughly, looks like some of handlers in the chain should be merged with explicit branching

2024-09-04 06:21 UTC, IvanIlyichev commented on shesha-core/src/Shesha.Framework/Domain/ShaUserRegistration.cs
> +        public virtual string AdditionalRegistrationInfoFormModule { get; set; }
Hi @OmolemoBlessingLethuloe. I see you use two columns for module and form name. Please change it to use **FormIdentifier** type instead like this: ```public virtual FormIdentifier AdditionalRegistrationForm { get; set; }```

2024-09-04 06:21 UTC, IvanIlyichev commented on shesha-core/src/Shesha.Application/Authorization/TokenAuthController.cs
> +                var redirectUrl = $"/no-auth/{registration.AdditionalRegistrationInfoFormModule}/{checkRegistration.AdditionalRegistrationInfoFormName}";
Hi @OmolemoBlessingLethuloe. **no-auth** route is specific to the front-end application, it should be moved to the front-end specific setting with **no-auth** as a default

2024-09-04 06:21 UTC, IvanIlyichev commented on shesha-core/src/Shesha.Framework/Otp/IOtpManager.cs
> +        Task<ISendPinResponse> SendPinAsync(SendPinInput input);
Hi @OmolemoBlessingLethuloe. What was a reason of removal of interface usage here? If it's not required for your task please revert the change, I know one of devs are busy with enhancements of the OTP functionality and this change may complicate merge. Initially interfaces used here to make services more generic

2024-11-19 08:42 UTC, AlexStepantsov commented on shesha-core/src/Shesha.Application/UserManagements/CreatePersonAccountDto.cs
> +        //[MinLength(5)]
Why did you comment this?

2024-11-19 08:49 UTC, AlexStepantsov requested changes

2024-11-19 08:49 UTC, AlexStepantsov commented on shesha-core/src/Shesha.NHibernate/Migrations/M20240902170200.cs
Why didn't you add the insertion of registration records for existing Persons? Now, a User Registration will always be created for new Person. So you need to add migration to add User Registration and for existing Persons

2024-11-21 11:23 UTC, AlexStepantsov approved these changes

2024-11-21 12:47 UTC, AlexStepantsov approved these changes

2024-11-21 12:49 UTC, AlexStepantsov approved these changes

2024-11-21 12:49 UTC, merged