removed conditional check before hiding formInfo panel
shesha-io/shesha-framework pull request #2325
Opened 2024-10-24 05:46 UTC by James-Baloyi

2024-10-25 07:34 UTC, IvanIlyichev requested changes
Hi @James-Baloyi. The code requires refactoring. Current implementation has multiple issues which make it unstable and complicate code readability.

1. If your code requires timeouts it should be set on the action (e.g. onClick set visible and start timeout to hide) but not as part of the useEffect.
2. avoid unneeded useEffects in general, current logic of the control is unpredictable especially taking in mind that this control uses common context and each formInfo block changes state of this context
2. comparison of boolean values using `myConst === true` doesn't make any sense and affect code readability
3. don't use misleading names of functions and variables, `toggleXXX` always means reversion of state, i.e. show if hidden and hide when visible

2024-10-30 10:23 UTC, James-Baloyi commented
Good afternoon, @IvanIlyichev - I've implemented the changes as requested

2024-11-01 08:02 UTC, IvanIlyichev requested changes
Hi @James-Baloyi. Build fails

2024-11-01 09:41 UTC, IvanIlyichev approved these changes

2024-11-01 09:41 UTC, merged